services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: discord-bot
    env_file:
      - .env
    networks:
      - proxy

networks:
  proxy:
    external: true
