services:
  hoshizune:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: hoshizune
    env_file:
      - .env
    networks:
      - proxy

networks:
  proxy:
    external: true
